# Gradle
org.gradle.jvmargs = -Xmx4G
org.gradle.daemon = false
org.gradle.parallel = true
org.gradle.caching = true
org.gradle.configuration-cache = false

# Minecraft / Fabric
parchment_minecraft_version = 1.20.1
parchment_mappings_version = 2023.09.03
minecraft_version = 1.20.1
fabric_loader_version = 0.17.2
fabric_api_version = 0.92.6+1.20.1

# Mod
mod_id = create_enchantment_industry
mod_artifact_id = create-enchantment-industry
mod_name = Create: Enchantment Industry
mod_license = LGPL-3.0-or-later
mod_version = 2.5.2
mod_group_id = plus.dragons.createenchantmentindustry
mod_authors = DragonsPlus
mod_description = Enchantment, Experience, Enhancement and Enlightening - with Create
mod_github = https://github.com/DragonsPlusMinecraft/CreateEnchantmentIndustry

# Core dependencies
conditional_mixin_version = 0.6.4
mixin_extras_version = 0.5.0
create_fabric_version = 6.0.8.1+build.1744-mc1.20.1
create_version_production = 6.0.8.1
create_version_range = >=6.0.8.1 <6.1.0
create_dragons_plus_version = 1.11.7-e
create_dragons_plus_mod_version = >=1.11.7-e
jei_version = 15.20.0.106

# Optional Zenith integration
zenith_version = 1.2.5-1.20.1
fakerlib_version = 0.1.4
zenith_attributes_version = 0.2.10
patchouli_version = 1.20.1-84.1-FABRIC
additional_entity_attributes_version = w03ppuef
cardinal_components_version = 5.2.2
player_ability_lib_version = 1.8.0
porting_lib_version = 2.3.13+1.20.1
fabric_asm_version = v2.3
